# Results for RQ1

In [41]:
import os 
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import prettytable

cwd = os.getcwd()
os.chdir('../../')
import errorAPI
from errorAPI.dataset import Dataset
os.chdir(cwd)

In [42]:
sql_string = 'postgresql://postgres:postgres@localhost:5432/error_detection'
dataset_stats = pd.read_sql_table("datasets", create_engine(sql_string)).iloc[:, 1:]

In [43]:
dataset_stats_show = dataset_stats.rename(columns={
    "name": "Dataset",
    "data_quality": "Data quality",
    "num_rows": "Rows",
    "num_columns": "Columns",
    "num_errors": "Number of errors"
})
dataset_stats_show["Total cells"] = dataset_stats_show["Rows"] * dataset_stats_show["Columns"]
dataset_stats_show["Data quality"] = dataset_stats_show["Data quality"].apply(lambda x: str(round(x * 100, 1)) + " %")

In [44]:
dataset_stats_show

        Dataset Data quality   Rows  Columns  Number of errors  Total cells
0        airbnb       85.4 %  18406       40            107625       736240
1         beers       83.5 %   2410       11              4362        26510
2           eeg       97.6 %  14980       15              5496       224700
3       flights       70.4 %   2376        7              4920        16632
4      hospital       97.5 %   1000       20               509        20000
5     marketing       78.7 %   8993       14             26815       125902
6         movie       63.3 %   6531        8             19174        52248
7        movies       98.8 %   7390       17              1501       125630
8        rayyan       91.4 %   1000       11               948        11000
9    restaurant       99.5 %  12007       11               635       132077
10  restaurants       99.9 %  28787       16               565       460592
11          toy       77.8 %      6        3                 4           18
12   university       97.4 %    210       18               100         3780
13     uscensus       99.1 %  32561       15              4262       488415

In [47]:
print(dataset_stats_show.to_latex(index=False))

\begin{tabular}{llrrrr}
\toprule
     Dataset & Data quality &   Rows &  Columns &  Number of errors &  Total cells \\
\midrule
      airbnb &       85.4 \% &  18406 &       40 &            107625 &       736240 \\
       beers &       83.5 \% &   2410 &       11 &              4362 &        26510 \\
         eeg &       97.6 \% &  14980 &       15 &              5496 &       224700 \\
     flights &       70.4 \% &   2376 &        7 &              4920 &        16632 \\
    hospital &       97.5 \% &   1000 &       20 &               509 &        20000 \\
   marketing &       78.7 \% &   8993 &       14 &             26815 &       125902 \\
       movie &       63.3 \% &   6531 &        8 &             19174 &        52248 \\
      movies &       98.8 \% &   7390 &       17 &              1501 &       125630 \\
      rayyan &       91.4 \% &   1000 &       11 &               948 &        11000 \\
  restaurant &       99.5 \% &  12007 &       11 &               635 &       132077 \\
 restaurants &       99.9 \% &  28787 &       16 &               565 &       460592 \\
         toy &       77.8 \% &      6 &        3 &                 4 &           18 \\
  university &       97.4 \% &    210 &       18 &               100 &         3780 \\
    uscensus &       99.1 \% &  32561 &       15 &              4262 &       488415 \\
\bottomrule
\end{tabular}